# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gen3tools.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(511, 589)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.tab_3)
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.frame = QtWidgets.QLineEdit(self.widget)
        self.frame.setObjectName("frame")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.frame)
        self.seed = QtWidgets.QLineEdit(self.widget)
        self.seed.setObjectName("seed")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.seed)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_45 = QtWidgets.QLabel(self.widget)
        self.label_45.setObjectName("label_45")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_45)
        self.seedPID = QtWidgets.QLineEdit(self.widget)
        self.seedPID.setObjectName("seedPID")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.seedPID)
        self.label_46 = QtWidgets.QLabel(self.widget)
        self.label_46.setObjectName("label_46")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_46)
        self.wildPID = QtWidgets.QLineEdit(self.widget)
        self.wildPID.setObjectName("wildPID")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.wildPID)
        self.verticalLayout_2.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.tab_3)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.updateButton = QtWidgets.QPushButton(self.widget_2)
        self.updateButton.setObjectName("updateButton")
        self.horizontalLayout.addWidget(self.updateButton)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.scrollArea = QtWidgets.QScrollArea(self.tab_3)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 479, 268))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents_4)
        self.plainTextEdit.setEnabled(False)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_3.addWidget(self.plainTextEdit)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_4.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_3 = QtWidgets.QWidget(self.tab_4)
        self.widget_3.setObjectName("widget_3")
        self.formLayout_2 = QtWidgets.QFormLayout(self.widget_3)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.raw = QtWidgets.QLineEdit(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.raw.setFont(font)
        self.raw.setObjectName("raw")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.raw)
        self.verticalLayout_4.addWidget(self.widget_3)
        self.line = QtWidgets.QFrame(self.tab_4)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.widget_4 = QtWidgets.QWidget(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout.setObjectName("gridLayout")
        self.checksum = QtWidgets.QLineEdit(self.widget_4)
        self.checksum.setObjectName("checksum")
        self.gridLayout.addWidget(self.checksum, 3, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget_4)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget_4)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.otId = QtWidgets.QLineEdit(self.widget_4)
        self.otId.setObjectName("otId")
        self.gridLayout.addWidget(self.otId, 0, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget_4)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget_4)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget_4)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.otName = QtWidgets.QLineEdit(self.widget_4)
        self.otName.setObjectName("otName")
        self.gridLayout.addWidget(self.otName, 1, 3, 1, 1)
        self.personality = QtWidgets.QLineEdit(self.widget_4)
        self.personality.setObjectName("personality")
        self.gridLayout.addWidget(self.personality, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget_4)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.isBadEgg = QtWidgets.QLineEdit(self.widget_4)
        self.isBadEgg.setObjectName("isBadEgg")
        self.gridLayout.addWidget(self.isBadEgg, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 2, 1, 1)
        self.nickname = QtWidgets.QLineEdit(self.widget_4)
        self.nickname.setObjectName("nickname")
        self.gridLayout.addWidget(self.nickname, 1, 1, 1, 1)
        self.isEgg = QtWidgets.QLineEdit(self.widget_4)
        self.isEgg.setObjectName("isEgg")
        self.gridLayout.addWidget(self.isEgg, 2, 3, 1, 1)
        self.order = QtWidgets.QLabel(self.widget_4)
        self.order.setText("N/A")
        self.order.setObjectName("order")
        self.gridLayout.addWidget(self.order, 3, 3, 1, 1)
        self.verticalLayout_4.addWidget(self.widget_4)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
        self.tabWidget_2.setSizePolicy(sizePolicy)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.formLayout_3 = QtWidgets.QFormLayout(self.tab_5)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_12 = QtWidgets.QLabel(self.tab_5)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.species = QtWidgets.QLineEdit(self.tab_5)
        self.species.setObjectName("species")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.species)
        self.label_13 = QtWidgets.QLabel(self.tab_5)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.label_14 = QtWidgets.QLabel(self.tab_5)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.label_15 = QtWidgets.QLabel(self.tab_5)
        self.label_15.setObjectName("label_15")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.label_16 = QtWidgets.QLabel(self.tab_5)
        self.label_16.setObjectName("label_16")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.heldItem = QtWidgets.QLineEdit(self.tab_5)
        self.heldItem.setObjectName("heldItem")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.heldItem)
        self.experience = QtWidgets.QLineEdit(self.tab_5)
        self.experience.setObjectName("experience")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.experience)
        self.ppBonuses = QtWidgets.QLineEdit(self.tab_5)
        self.ppBonuses.setObjectName("ppBonuses")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.ppBonuses)
        self.friendship = QtWidgets.QLineEdit(self.tab_5)
        self.friendship.setObjectName("friendship")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.friendship)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pp2 = QtWidgets.QLineEdit(self.tab_6)
        self.pp2.setObjectName("pp2")
        self.gridLayout_2.addWidget(self.pp2, 2, 3, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab_6)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 1, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab_6)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 2, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab_6)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 0, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab_6)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 1, 2, 1, 1)
        self.pp1 = QtWidgets.QLineEdit(self.tab_6)
        self.pp1.setObjectName("pp1")
        self.gridLayout_2.addWidget(self.pp1, 1, 3, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tab_6)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 2, 2, 1, 1)
        self.move2 = QtWidgets.QLineEdit(self.tab_6)
        self.move2.setObjectName("move2")
        self.gridLayout_2.addWidget(self.move2, 2, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_6)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 0, 2, 1, 1)
        self.move0 = QtWidgets.QLineEdit(self.tab_6)
        self.move0.setObjectName("move0")
        self.gridLayout_2.addWidget(self.move0, 0, 1, 1, 1)
        self.pp0 = QtWidgets.QLineEdit(self.tab_6)
        self.pp0.setObjectName("pp0")
        self.gridLayout_2.addWidget(self.pp0, 0, 3, 1, 1)
        self.move1 = QtWidgets.QLineEdit(self.tab_6)
        self.move1.setObjectName("move1")
        self.gridLayout_2.addWidget(self.move1, 1, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab_6)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 3, 0, 1, 1)
        self.move3 = QtWidgets.QLineEdit(self.tab_6)
        self.move3.setObjectName("move3")
        self.gridLayout_2.addWidget(self.move3, 3, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tab_6)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 3, 2, 1, 1)
        self.pp3 = QtWidgets.QLineEdit(self.tab_6)
        self.pp3.setObjectName("pp3")
        self.gridLayout_2.addWidget(self.pp3, 3, 3, 1, 1)
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_25 = QtWidgets.QLabel(self.tab_7)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 0, 0, 1, 1)
        self.hpEV = QtWidgets.QLineEdit(self.tab_7)
        self.hpEV.setObjectName("hpEV")
        self.gridLayout_3.addWidget(self.hpEV, 0, 1, 1, 1)
        self.cool = QtWidgets.QLineEdit(self.tab_7)
        self.cool.setObjectName("cool")
        self.gridLayout_3.addWidget(self.cool, 4, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.tab_7)
        self.label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName("label_32")
        self.gridLayout_3.addWidget(self.label_32, 4, 2, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.tab_7)
        self.label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout_3.addWidget(self.label_31, 4, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.tab_7)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 0, 4, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.tab_7)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 0, 2, 1, 1)
        self.attackEV = QtWidgets.QLineEdit(self.tab_7)
        self.attackEV.setObjectName("attackEV")
        self.gridLayout_3.addWidget(self.attackEV, 0, 3, 1, 1)
        self.beauty = QtWidgets.QLineEdit(self.tab_7)
        self.beauty.setObjectName("beauty")
        self.gridLayout_3.addWidget(self.beauty, 4, 3, 1, 1)
        self.defenseEV = QtWidgets.QLineEdit(self.tab_7)
        self.defenseEV.setObjectName("defenseEV")
        self.gridLayout_3.addWidget(self.defenseEV, 0, 5, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.tab_7)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 1, 0, 1, 1)
        self.speedEV = QtWidgets.QLineEdit(self.tab_7)
        self.speedEV.setObjectName("speedEV")
        self.gridLayout_3.addWidget(self.speedEV, 1, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.tab_7)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 1, 2, 1, 1)
        self.spAttackEV = QtWidgets.QLineEdit(self.tab_7)
        self.spAttackEV.setObjectName("spAttackEV")
        self.gridLayout_3.addWidget(self.spAttackEV, 1, 3, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.tab_7)
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 1, 4, 1, 1)
        self.spDefenseEV = QtWidgets.QLineEdit(self.tab_7)
        self.spDefenseEV.setObjectName("spDefenseEV")
        self.gridLayout_3.addWidget(self.spDefenseEV, 1, 5, 1, 1)
        self.cute = QtWidgets.QLineEdit(self.tab_7)
        self.cute.setObjectName("cute")
        self.gridLayout_3.addWidget(self.cute, 4, 5, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.tab_7)
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout_3.addWidget(self.label_33, 4, 4, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.tab_7)
        self.label_34.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName("label_34")
        self.gridLayout_3.addWidget(self.label_34, 5, 0, 1, 1)
        self.smart = QtWidgets.QLineEdit(self.tab_7)
        self.smart.setObjectName("smart")
        self.gridLayout_3.addWidget(self.smart, 5, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.tab_7)
        self.label_35.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName("label_35")
        self.gridLayout_3.addWidget(self.label_35, 5, 2, 1, 1)
        self.tough = QtWidgets.QLineEdit(self.tab_7)
        self.tough.setObjectName("tough")
        self.gridLayout_3.addWidget(self.tough, 5, 3, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.tab_7)
        self.label_36.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName("label_36")
        self.gridLayout_3.addWidget(self.label_36, 5, 4, 1, 1)
        self.sheen = QtWidgets.QLineEdit(self.tab_7)
        self.sheen.setObjectName("sheen")
        self.gridLayout_3.addWidget(self.sheen, 5, 5, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.tab_7)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 3, 0, 1, 6)
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_8)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_38 = QtWidgets.QLabel(self.tab_8)
        self.label_38.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_38.setObjectName("label_38")
        self.gridLayout_4.addWidget(self.label_38, 0, 2, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.tab_8)
        self.label_40.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_40.setObjectName("label_40")
        self.gridLayout_4.addWidget(self.label_40, 1, 0, 1, 1)
        self.pokerus = QtWidgets.QLineEdit(self.tab_8)
        self.pokerus.setObjectName("pokerus")
        self.gridLayout_4.addWidget(self.pokerus, 0, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.tab_8)
        self.label_37.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName("label_37")
        self.gridLayout_4.addWidget(self.label_37, 0, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.tab_8)
        self.label_39.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_39.setObjectName("label_39")
        self.gridLayout_4.addWidget(self.label_39, 0, 4, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.tab_8)
        self.label_43.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_43.setObjectName("label_43")
        self.gridLayout_4.addWidget(self.label_43, 2, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.tab_8)
        self.label_41.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_41.setObjectName("label_41")
        self.gridLayout_4.addWidget(self.label_41, 1, 2, 1, 1)
        self.metLevel = QtWidgets.QLineEdit(self.tab_8)
        self.metLevel.setObjectName("metLevel")
        self.gridLayout_4.addWidget(self.metLevel, 0, 5, 1, 1)
        self.metGame = QtWidgets.QLineEdit(self.tab_8)
        self.metGame.setObjectName("metGame")
        self.gridLayout_4.addWidget(self.metGame, 1, 1, 1, 1)
        self.pokeBall = QtWidgets.QLineEdit(self.tab_8)
        self.pokeBall.setObjectName("pokeBall")
        self.gridLayout_4.addWidget(self.pokeBall, 1, 3, 1, 1)
        self.subIsEgg = QtWidgets.QLineEdit(self.tab_8)
        self.subIsEgg.setObjectName("subIsEgg")
        self.gridLayout_4.addWidget(self.subIsEgg, 2, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.tab_8)
        self.label_44.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_44.setObjectName("label_44")
        self.gridLayout_4.addWidget(self.label_44, 2, 2, 1, 1)
        self.metLocation = QtWidgets.QLineEdit(self.tab_8)
        self.metLocation.setObjectName("metLocation")
        self.gridLayout_4.addWidget(self.metLocation, 0, 3, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.tab_8)
        self.label_42.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_42.setObjectName("label_42")
        self.gridLayout_4.addWidget(self.label_42, 1, 4, 1, 1)
        self.otGender = QtWidgets.QLineEdit(self.tab_8)
        self.otGender.setObjectName("otGender")
        self.gridLayout_4.addWidget(self.otGender, 1, 5, 1, 1)
        self.altAbility = QtWidgets.QLineEdit(self.tab_8)
        self.altAbility.setObjectName("altAbility")
        self.gridLayout_4.addWidget(self.altAbility, 2, 3, 1, 1)
        self.tabWidget_2.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_9)
        self.gridLayout_5.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_5.setVerticalSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.mem15 = QtWidgets.QLineEdit(self.tab_9)
        self.mem15.setFrame(False)
        self.mem15.setObjectName("mem15")
        self.gridLayout_5.addWidget(self.mem15, 3, 3, 1, 1)
        self.mem14 = QtWidgets.QLineEdit(self.tab_9)
        self.mem14.setFrame(False)
        self.mem14.setObjectName("mem14")
        self.gridLayout_5.addWidget(self.mem14, 3, 2, 1, 1)
        self.mem6 = QtWidgets.QLineEdit(self.tab_9)
        self.mem6.setFrame(False)
        self.mem6.setObjectName("mem6")
        self.gridLayout_5.addWidget(self.mem6, 1, 2, 1, 1)
        self.mem8 = QtWidgets.QLineEdit(self.tab_9)
        self.mem8.setFrame(False)
        self.mem8.setObjectName("mem8")
        self.gridLayout_5.addWidget(self.mem8, 2, 0, 1, 1)
        self.mem13 = QtWidgets.QLineEdit(self.tab_9)
        self.mem13.setFrame(False)
        self.mem13.setObjectName("mem13")
        self.gridLayout_5.addWidget(self.mem13, 3, 1, 1, 1)
        self.mem3 = QtWidgets.QLineEdit(self.tab_9)
        self.mem3.setFrame(False)
        self.mem3.setObjectName("mem3")
        self.gridLayout_5.addWidget(self.mem3, 0, 3, 1, 1)
        self.mem11 = QtWidgets.QLineEdit(self.tab_9)
        self.mem11.setFrame(False)
        self.mem11.setObjectName("mem11")
        self.gridLayout_5.addWidget(self.mem11, 2, 3, 1, 1)
        self.mem1 = QtWidgets.QLineEdit(self.tab_9)
        self.mem1.setFrame(False)
        self.mem1.setObjectName("mem1")
        self.gridLayout_5.addWidget(self.mem1, 0, 1, 1, 1)
        self.mem5 = QtWidgets.QLineEdit(self.tab_9)
        self.mem5.setFrame(False)
        self.mem5.setObjectName("mem5")
        self.gridLayout_5.addWidget(self.mem5, 1, 1, 1, 1)
        self.mem4 = QtWidgets.QLineEdit(self.tab_9)
        self.mem4.setFrame(False)
        self.mem4.setObjectName("mem4")
        self.gridLayout_5.addWidget(self.mem4, 1, 0, 1, 1)
        self.mem9 = QtWidgets.QLineEdit(self.tab_9)
        self.mem9.setFrame(False)
        self.mem9.setObjectName("mem9")
        self.gridLayout_5.addWidget(self.mem9, 2, 1, 1, 1)
        self.mem12 = QtWidgets.QLineEdit(self.tab_9)
        self.mem12.setFrame(False)
        self.mem12.setObjectName("mem12")
        self.gridLayout_5.addWidget(self.mem12, 3, 0, 1, 1)
        self.mem7 = QtWidgets.QLineEdit(self.tab_9)
        self.mem7.setFrame(False)
        self.mem7.setObjectName("mem7")
        self.gridLayout_5.addWidget(self.mem7, 1, 3, 1, 1)
        self.mem2 = QtWidgets.QLineEdit(self.tab_9)
        self.mem2.setFrame(False)
        self.mem2.setObjectName("mem2")
        self.gridLayout_5.addWidget(self.mem2, 0, 2, 1, 1)
        self.mem0 = QtWidgets.QLineEdit(self.tab_9)
        self.mem0.setFrame(False)
        self.mem0.setObjectName("mem0")
        self.gridLayout_5.addWidget(self.mem0, 0, 0, 1, 1)
        self.mem10 = QtWidgets.QLineEdit(self.tab_9)
        self.mem10.setFrame(False)
        self.mem10.setObjectName("mem10")
        self.gridLayout_5.addWidget(self.mem10, 2, 2, 1, 1)
        self.mem16 = QtWidgets.QLineEdit(self.tab_9)
        self.mem16.setFrame(False)
        self.mem16.setObjectName("mem16")
        self.gridLayout_5.addWidget(self.mem16, 4, 0, 1, 1)
        self.mem17 = QtWidgets.QLineEdit(self.tab_9)
        self.mem17.setFrame(False)
        self.mem17.setObjectName("mem17")
        self.gridLayout_5.addWidget(self.mem17, 4, 1, 1, 1)
        self.mem18 = QtWidgets.QLineEdit(self.tab_9)
        self.mem18.setFrame(False)
        self.mem18.setObjectName("mem18")
        self.gridLayout_5.addWidget(self.mem18, 4, 2, 1, 1)
        self.mem19 = QtWidgets.QLineEdit(self.tab_9)
        self.mem19.setFrame(False)
        self.mem19.setObjectName("mem19")
        self.gridLayout_5.addWidget(self.mem19, 4, 3, 1, 1)
        self.tabWidget_2.addTab(self.tab_9, "")
        self.verticalLayout_4.addWidget(self.tabWidget_2)
        self.legalButton = QtWidgets.QPushButton(self.tab_4)
        self.legalButton.setObjectName("legalButton")
        self.verticalLayout_4.addWidget(self.legalButton)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_5 = QtWidgets.QWidget(self.tab)
        self.widget_5.setObjectName("widget_5")
        self.formLayout_4 = QtWidgets.QFormLayout(self.widget_5)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_47 = QtWidgets.QLabel(self.widget_5)
        self.label_47.setObjectName("label_47")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_47)
        self.aceID = QtWidgets.QLineEdit(self.widget_5)
        self.aceID.setObjectName("aceID")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.aceID)
        self.label_48 = QtWidgets.QLabel(self.widget_5)
        self.label_48.setObjectName("label_48")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_48)
        self.scentFrames = QtWidgets.QLineEdit(self.widget_5)
        self.scentFrames.setObjectName("scentFrames")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.scentFrames)
        self.verticalLayout_5.addWidget(self.widget_5)
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tabWidget_3.sizePolicy().hasHeightForWidth())
        self.tabWidget_3.setSizePolicy(sizePolicy)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.tab_13)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.glitchButton = QtWidgets.QPushButton(self.tab_13)
        self.glitchButton.setObjectName("glitchButton")
        self.verticalLayout_23.addWidget(self.glitchButton)
        self.tabWidget_3.addTab(self.tab_13, "")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.tabWidget_3.addTab(self.tab_14, "")
        self.verticalLayout_5.addWidget(self.tabWidget_3)
        self.widget_7 = QtWidgets.QWidget(self.tab)
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_7)
        self.gridLayout_6.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_6.setSpacing(3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_9 = QtWidgets.QFrame(self.widget_7)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.spinda7 = QtWidgets.QLabel(self.frame_9)
        self.spinda7.setMinimumSize(QtCore.QSize(64, 64))
        self.spinda7.setMaximumSize(QtCore.QSize(64, 64))
        self.spinda7.setText("")
        self.spinda7.setScaledContents(True)
        self.spinda7.setAlignment(QtCore.Qt.AlignCenter)
        self.spinda7.setObjectName("spinda7")
        self.verticalLayout_15.addWidget(self.spinda7)
        self.gridLayout_6.addWidget(self.frame_9, 1, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.frame_2 = QtWidgets.QFrame(self.widget_7)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.spinda0 = QtWidgets.QLabel(self.frame_2)
        self.spinda0.setMinimumSize(QtCore.QSize(64, 64))
        self.spinda0.setMaximumSize(QtCore.QSize(64, 64))
        self.spinda0.setText("")
        self.spinda0.setScaledContents(True)
        self.spinda0.setAlignment(QtCore.Qt.AlignCenter)
        self.spinda0.setObjectName("spinda0")
        self.verticalLayout_6.addWidget(self.spinda0)
        self.gridLayout_6.addWidget(self.frame_2, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.frame_3 = QtWidgets.QFrame(self.widget_7)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.spinda1 = QtWidgets.QLabel(self.frame_3)
        self.spinda1.setMinimumSize(QtCore.QSize(64, 64))
        self.spinda1.setMaximumSize(QtCore.QSize(64, 64))
        self.spinda1.setText("")
        self.spinda1.setScaledContents(True)
        self.spinda1.setAlignment(QtCore.Qt.AlignCenter)
        self.spinda1.setObjectName("spinda1")
        self.verticalLayout_7.addWidget(self.spinda1)
        self.gridLayout_6.addWidget(self.frame_3, 0, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.frame_11 = QtWidgets.QFrame(self.widget_7)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.spinda9 = QtWidgets.QLabel(self.frame_11)
        self.spinda9.setMinimumSize(QtCore.QSize(64, 64))
        self.spinda9.setMaximumSize(QtCore.QSize(64, 64))
        self.spinda9.setText("")
        self.spinda9.setScaledContents(True)
        self.spinda9.setAlignment(QtCore.Qt.AlignCenter)
        self.spinda9.setObjectName("spinda9")
        self.verticalLayout_17.addWidget(self.spinda9)
        self.gridLayout_6.addWidget(self.frame_11, 1, 4, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.frame_5 = QtWidgets.QFrame(self.widget_7)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.spinda3 = QtWidgets.QLabel(self.frame_5)
        self.spinda3.setMinimumSize(QtCore.QSize(64, 64))
        self.spinda3.setMaximumSize(QtCore.QSize(64, 64))
        self.spinda3.setText("")
        self.spinda3.setScaledContents(True)
        self.spinda3.setAlignment(QtCore.Qt.AlignCenter)
        self.spinda3.setObjectName("spinda3")
        self.verticalLayout_9.addWidget(self.spinda3)
        self.gridLayout_6.addWidget(self.frame_5, 0, 3, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.frame_4 = QtWidgets.QFrame(self.widget_7)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.spinda2 = QtWidgets.QLabel(self.frame_4)
        self.spinda2.setMinimumSize(QtCore.QSize(64, 64))
        self.spinda2.setMaximumSize(QtCore.QSize(64, 64))
        self.spinda2.setText("")
        self.spinda2.setScaledContents(True)
        self.spinda2.setAlignment(QtCore.Qt.AlignCenter)
        self.spinda2.setObjectName("spinda2")
        self.verticalLayout_8.addWidget(self.spinda2)
        self.gridLayout_6.addWidget(self.frame_4, 0, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.frame_10 = QtWidgets.QFrame(self.widget_7)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.spinda8 = QtWidgets.QLabel(self.frame_10)
        self.spinda8.setMinimumSize(QtCore.QSize(64, 64))
        self.spinda8.setMaximumSize(QtCore.QSize(64, 64))
        self.spinda8.setText("")
        self.spinda8.setScaledContents(True)
        self.spinda8.setAlignment(QtCore.Qt.AlignCenter)
        self.spinda8.setObjectName("spinda8")
        self.verticalLayout_16.addWidget(self.spinda8)
        self.gridLayout_6.addWidget(self.frame_10, 1, 3, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.frame_7 = QtWidgets.QFrame(self.widget_7)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.spinda5 = QtWidgets.QLabel(self.frame_7)
        self.spinda5.setMinimumSize(QtCore.QSize(64, 64))
        self.spinda5.setMaximumSize(QtCore.QSize(64, 64))
        self.spinda5.setText("")
        self.spinda5.setScaledContents(True)
        self.spinda5.setAlignment(QtCore.Qt.AlignCenter)
        self.spinda5.setObjectName("spinda5")
        self.verticalLayout_11.addWidget(self.spinda5)
        self.gridLayout_6.addWidget(self.frame_7, 1, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.frame_8 = QtWidgets.QFrame(self.widget_7)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.spinda6 = QtWidgets.QLabel(self.frame_8)
        self.spinda6.setMinimumSize(QtCore.QSize(64, 64))
        self.spinda6.setMaximumSize(QtCore.QSize(64, 64))
        self.spinda6.setText("")
        self.spinda6.setScaledContents(True)
        self.spinda6.setAlignment(QtCore.Qt.AlignCenter)
        self.spinda6.setObjectName("spinda6")
        self.verticalLayout_14.addWidget(self.spinda6)
        self.gridLayout_6.addWidget(self.frame_8, 1, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.frame_6 = QtWidgets.QFrame(self.widget_7)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.spinda4 = QtWidgets.QLabel(self.frame_6)
        self.spinda4.setMinimumSize(QtCore.QSize(64, 64))
        self.spinda4.setMaximumSize(QtCore.QSize(64, 64))
        self.spinda4.setText("")
        self.spinda4.setScaledContents(True)
        self.spinda4.setAlignment(QtCore.Qt.AlignCenter)
        self.spinda4.setObjectName("spinda4")
        self.verticalLayout_10.addWidget(self.spinda4)
        self.gridLayout_6.addWidget(self.frame_6, 0, 4, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.frame_12 = QtWidgets.QFrame(self.widget_7)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.spinda10 = QtWidgets.QLabel(self.frame_12)
        self.spinda10.setMinimumSize(QtCore.QSize(64, 64))
        self.spinda10.setMaximumSize(QtCore.QSize(64, 64))
        self.spinda10.setText("")
        self.spinda10.setScaledContents(True)
        self.spinda10.setAlignment(QtCore.Qt.AlignCenter)
        self.spinda10.setObjectName("spinda10")
        self.verticalLayout_18.addWidget(self.spinda10)
        self.gridLayout_6.addWidget(self.frame_12, 2, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.frame_13 = QtWidgets.QFrame(self.widget_7)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.spinda11 = QtWidgets.QLabel(self.frame_13)
        self.spinda11.setMinimumSize(QtCore.QSize(64, 64))
        self.spinda11.setMaximumSize(QtCore.QSize(64, 64))
        self.spinda11.setText("")
        self.spinda11.setScaledContents(True)
        self.spinda11.setAlignment(QtCore.Qt.AlignCenter)
        self.spinda11.setObjectName("spinda11")
        self.verticalLayout_19.addWidget(self.spinda11)
        self.gridLayout_6.addWidget(self.frame_13, 2, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.frame_14 = QtWidgets.QFrame(self.widget_7)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.spinda12 = QtWidgets.QLabel(self.frame_14)
        self.spinda12.setMinimumSize(QtCore.QSize(64, 64))
        self.spinda12.setMaximumSize(QtCore.QSize(64, 64))
        self.spinda12.setText("")
        self.spinda12.setScaledContents(True)
        self.spinda12.setAlignment(QtCore.Qt.AlignCenter)
        self.spinda12.setObjectName("spinda12")
        self.verticalLayout_20.addWidget(self.spinda12)
        self.gridLayout_6.addWidget(self.frame_14, 2, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.frame_15 = QtWidgets.QFrame(self.widget_7)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.spinda13 = QtWidgets.QLabel(self.frame_15)
        self.spinda13.setMinimumSize(QtCore.QSize(64, 64))
        self.spinda13.setMaximumSize(QtCore.QSize(64, 64))
        self.spinda13.setText("")
        self.spinda13.setScaledContents(True)
        self.spinda13.setAlignment(QtCore.Qt.AlignCenter)
        self.spinda13.setObjectName("spinda13")
        self.verticalLayout_21.addWidget(self.spinda13)
        self.gridLayout_6.addWidget(self.frame_15, 2, 3, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.frame_16 = QtWidgets.QFrame(self.widget_7)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.spinda14 = QtWidgets.QLabel(self.frame_16)
        self.spinda14.setMinimumSize(QtCore.QSize(64, 64))
        self.spinda14.setMaximumSize(QtCore.QSize(64, 64))
        self.spinda14.setText("")
        self.spinda14.setScaledContents(True)
        self.spinda14.setAlignment(QtCore.Qt.AlignCenter)
        self.spinda14.setObjectName("spinda14")
        self.verticalLayout_22.addWidget(self.spinda14)
        self.gridLayout_6.addWidget(self.frame_16, 2, 4, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.verticalLayout_5.addWidget(self.widget_7)
        self.widget_6 = QtWidgets.QWidget(self.tab)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_68 = QtWidgets.QLabel(self.widget_6)
        self.label_68.setObjectName("label_68")
        self.gridLayout_7.addWidget(self.label_68, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.spindaFrame = QtWidgets.QLabel(self.widget_6)
        self.spindaFrame.setObjectName("spindaFrame")
        self.gridLayout_7.addWidget(self.spindaFrame, 0, 3, 1, 1)
        self.label_70 = QtWidgets.QLabel(self.widget_6)
        self.label_70.setObjectName("label_70")
        self.gridLayout_7.addWidget(self.label_70, 0, 2, 1, 1, QtCore.Qt.AlignRight)
        self.spindaPID = QtWidgets.QLabel(self.widget_6)
        self.spindaPID.setObjectName("spindaPID")
        self.gridLayout_7.addWidget(self.spindaPID, 0, 1, 1, 1)
        self.label_72 = QtWidgets.QLabel(self.widget_6)
        self.label_72.setObjectName("label_72")
        self.gridLayout_7.addWidget(self.label_72, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.spindaGender = QtWidgets.QLabel(self.widget_6)
        self.spindaGender.setObjectName("spindaGender")
        self.gridLayout_7.addWidget(self.spindaGender, 1, 1, 1, 1)
        self.label_74 = QtWidgets.QLabel(self.widget_6)
        self.label_74.setObjectName("label_74")
        self.gridLayout_7.addWidget(self.label_74, 1, 2, 1, 1, QtCore.Qt.AlignRight)
        self.spindaNature = QtWidgets.QLabel(self.widget_6)
        self.spindaNature.setObjectName("spindaNature")
        self.gridLayout_7.addWidget(self.spindaNature, 1, 3, 1, 1)
        self.verticalLayout_5.addWidget(self.widget_6)
        self.widget_8 = QtWidgets.QWidget(self.tab)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_49 = QtWidgets.QLabel(self.widget_8)
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_2.addWidget(self.label_49)
        self.lineEdit = QtWidgets.QLineEdit(self.widget_8)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.widget_8)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout_5.addWidget(self.widget_8)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 511, 29))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.tabWidget_2.setCurrentIndex(2)
        self.tabWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gen3Tools"))
        self.label.setText(_translate("MainWindow", "Frame:"))
        self.label_2.setText(_translate("MainWindow", "Seed:"))
        self.label_45.setText(_translate("MainWindow", "PID:"))
        self.label_46.setText(_translate("MainWindow", "Wild PID:"))
        self.updateButton.setText(_translate("MainWindow", "Update"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Rng"))
        self.label_3.setText(_translate("MainWindow", "Raw:"))
        self.label_7.setText(_translate("MainWindow", "otName:"))
        self.label_5.setText(_translate("MainWindow", "otID:"))
        self.label_4.setText(_translate("MainWindow", "PID:"))
        self.label_10.setText(_translate("MainWindow", "Checksum:"))
        self.label_11.setText(_translate("MainWindow", "Order:"))
        self.label_6.setText(_translate("MainWindow", "Nickname:"))
        self.label_8.setText(_translate("MainWindow", "isBadEgg:"))
        self.label_9.setText(_translate("MainWindow", "isEgg:"))
        self.label_12.setText(_translate("MainWindow", "Species:"))
        self.label_13.setText(_translate("MainWindow", "Item:"))
        self.label_14.setText(_translate("MainWindow", "Exp:"))
        self.label_15.setText(_translate("MainWindow", "PP Bonus:"))
        self.label_16.setText(_translate("MainWindow", "Friendship:"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Growth"))
        self.label_19.setText(_translate("MainWindow", "Move 2:"))
        self.label_21.setText(_translate("MainWindow", "Move 3:"))
        self.label_17.setText(_translate("MainWindow", "Move 1:"))
        self.label_20.setText(_translate("MainWindow", "PP:"))
        self.label_22.setText(_translate("MainWindow", "PP:"))
        self.label_18.setText(_translate("MainWindow", "PP:"))
        self.label_23.setText(_translate("MainWindow", "Move 4:"))
        self.label_24.setText(_translate("MainWindow", "PP:"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Attacks"))
        self.label_25.setText(_translate("MainWindow", "HP:"))
        self.label_32.setText(_translate("MainWindow", "Beauty:"))
        self.label_31.setText(_translate("MainWindow", "Cool:"))
        self.label_27.setText(_translate("MainWindow", "Defense:"))
        self.label_26.setText(_translate("MainWindow", "Attack:"))
        self.label_28.setText(_translate("MainWindow", "Speed:"))
        self.label_29.setText(_translate("MainWindow", "Sp. Attack:"))
        self.label_30.setText(_translate("MainWindow", "Sp. Defense:"))
        self.label_33.setText(_translate("MainWindow", "Cute:"))
        self.label_34.setText(_translate("MainWindow", "Smart:"))
        self.label_35.setText(_translate("MainWindow", "Tough:"))
        self.label_36.setText(_translate("MainWindow", "Sheen:"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("MainWindow", "EVs/Condition"))
        self.label_38.setText(_translate("MainWindow", "Met Location:"))
        self.label_40.setText(_translate("MainWindow", "Met Game:"))
        self.label_37.setText(_translate("MainWindow", "Pokerus:"))
        self.label_39.setText(_translate("MainWindow", "Met Lvl:"))
        self.label_43.setText(_translate("MainWindow", "Is Egg:"))
        self.label_41.setText(_translate("MainWindow", "Pokeball:"))
        self.label_44.setText(_translate("MainWindow", "Alt Ability:"))
        self.label_42.setText(_translate("MainWindow", "OT Gender:"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("MainWindow", "Misc."))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), _translate("MainWindow", "Memory"))
        self.legalButton.setText(_translate("MainWindow", "Force Legal"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Pokemon"))
        self.label_47.setText(_translate("MainWindow", "otID:"))
        self.label_48.setText(_translate("MainWindow", "Offset:"))
        self.scentFrames.setText(_translate("MainWindow", "267"))
        self.glitchButton.setText(_translate("MainWindow", "Find Glitch Spinda"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_13), _translate("MainWindow", "Glitch Move"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_14), _translate("MainWindow", "Bootstrap"))
        self.label_68.setText(_translate("MainWindow", "PID:"))
        self.spindaFrame.setText(_translate("MainWindow", "N/A"))
        self.label_70.setText(_translate("MainWindow", "Frame:"))
        self.spindaPID.setText(_translate("MainWindow", "N/A"))
        self.label_72.setText(_translate("MainWindow", "Gender:"))
        self.spindaGender.setText(_translate("MainWindow", "N/A"))
        self.label_74.setText(_translate("MainWindow", "Nature:"))
        self.spindaNature.setText(_translate("MainWindow", "N/A"))
        self.label_49.setText(_translate("MainWindow", "#:"))
        self.lineEdit.setText(_translate("MainWindow", "15"))
        self.pushButton.setText(_translate("MainWindow", "Next"))
        self.pushButton_2.setText(_translate("MainWindow", "Previous"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "ACE"))

